version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest

python:
   install:
      - requirements: requirements_docs.txt
      - method: pip
        path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py

formats: all
