version: 2

python:
   version: 3.7
   install:
      - requirements: requirements_docs.txt
      - method: pip
        path: .

sphinx:
  builder: html
  configuration: docs/source/conf.py

formats: all
