version: 2

python:
   version: 3.7
   install:
      - requirements: requirements_docs.txt
      - method: pip
        path: .
      - method: setuptools
        path: package

sphinx:
  builder: html
  configuration: docs/conf.py

formats: all
