# Copyright 2019-2026 Yuhui
#
# Licensed under the GNU General Public License, Version 3.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.gnu.org/licenses/gpl-3.0.html
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Constants for all Environment-related APIs."""

from datetime import datetime

from ..constants import BASE_V2_API_ENDPOINT
from ..timezone import datetime_as_sgt

AIR_TEMPERATURE_API_ENDPOINT = f'{BASE_V2_API_ENDPOINT}/air-temperature'
FOUR_DAY_WEATHER_FORECAST_API_ENDPOINT = \
    f'{BASE_V2_API_ENDPOINT}/four-day-outlook'
PM25_API_ENDPOINT = f'{BASE_V2_API_ENDPOINT}/pm25'
PSI_API_ENDPOINT = f'{BASE_V2_API_ENDPOINT}/psi'
RAINFALL_API_ENDPOINT = f'{BASE_V2_API_ENDPOINT}/rainfall'
RELATIVE_HUMIDITY_API_ENDPOINT = f'{BASE_V2_API_ENDPOINT}/relative-humidity'
TWENTY_FOUR_HOUR_WEATHER_FORECAST_API_ENDPOINT = \
    f'{BASE_V2_API_ENDPOINT}/twenty-four-hr-forecast'
TWO_HOUR_WEATHER_FORECAST_API_ENDPOINT = \
    f'{BASE_V2_API_ENDPOINT}/two-hr-forecast'
UV_INDEX_API_ENDPOINT = f'{BASE_V2_API_ENDPOINT}/uv'
WIND_DIRECTION_API_ENDPOINT = f'{BASE_V2_API_ENDPOINT}/wind-direction'
WIND_SPEED_API_ENDPOINT = f'{BASE_V2_API_ENDPOINT}/wind-speed'

WEATHER_API_ENDPOINT = f'{BASE_V2_API_ENDPOINT}/weather'
FLOOD_ALERTS_API_ENDPOINT = f'{WEATHER_API_ENDPOINT}/flood-alerts'

LIGHTNING_DEFAULT_PARAMS = {
    'api': 'lightning',
}
WBGT_DEFAULT_PARAMS = {
    'api': 'wbgt',
}

WIND_SPEED_SANITISE_IGNORE_KEYS = [
    'stations[].id',
    'stations[].deviceId',
    'readings[].data[].stationId',
]

AIR_TEMPERATURE_MIN_DATETIME = datetime_as_sgt(datetime(2016, 5, 1, 0, 0, 0))
FOUR_DAY_WEATHER_FORECAST_MIN_DATETIME = datetime_as_sgt(
    datetime(2016, 3, 1, 0, 0, 0),
)
LIGHTNING_MIN_DATETIME = datetime_as_sgt(datetime(2025, 2, 1, 0, 0, 0))
PM25_MIN_DATETIME = datetime_as_sgt(datetime(2016, 2, 1, 0, 0, 0))
PSI_MIN_DATETIME = datetime_as_sgt(datetime(2016, 2, 1, 0, 0, 0))
RAINFALL_MIN_DATETIME = datetime_as_sgt(datetime(2016, 12, 1, 0, 0, 0))
RELATIVE_HUMIDITY_MIN_DATETIME = datetime_as_sgt(
    datetime(2016, 11, 1, 0, 0, 0),
)
TWENTY_FOUR_HOUR_WEATHER_FORECAST_MIN_DATETIME = datetime_as_sgt(
    datetime(2016, 3, 1, 0, 0, 0),
)
TWO_HOUR_WEATHER_FORECAST_MIN_DATETIME = datetime_as_sgt(
    datetime(2016, 3, 1, 0, 0, 0),
)
UV_MIN_DATETIME = datetime_as_sgt(datetime(2016, 3, 1, 0, 0, 0))
WBGT_MIN_DATETIME = datetime_as_sgt(datetime(2025, 2, 1, 0, 0, 0))
WIND_DIRECTION_MIN_DATETIME = datetime_as_sgt(datetime(2016, 11, 1, 0, 0, 0))
WIND_SPEED_MIN_DATETIME = datetime_as_sgt(datetime(2016, 12, 1, 0, 0, 0))

INVALID_DATETIME_ERROR_MESSAGE_FORMAT = 'date must be on or after {}.'
INVALID_AIR_TEMPERATURE_DATETIME_ERROR_MESSAGE = \
    INVALID_DATETIME_ERROR_MESSAGE_FORMAT.format(
        AIR_TEMPERATURE_MIN_DATETIME,
    )
INVALID_FOUR_DAY_WEATHER_FORECAST_DATETIME_ERROR_MESSAGE = \
    INVALID_DATETIME_ERROR_MESSAGE_FORMAT.format(
        FOUR_DAY_WEATHER_FORECAST_MIN_DATETIME,
    )
INVALID_LIGHTNING_DATETIME_ERROR_MESSAGE = \
    INVALID_DATETIME_ERROR_MESSAGE_FORMAT.format(
        LIGHTNING_MIN_DATETIME,
    )
INVALID_PM25_DATETIME_ERROR_MESSAGE = \
    INVALID_DATETIME_ERROR_MESSAGE_FORMAT.format(
        PM25_MIN_DATETIME,
    )
INVALID_PSI_DATETIME_ERROR_MESSAGE = \
    INVALID_DATETIME_ERROR_MESSAGE_FORMAT.format(
        PSI_MIN_DATETIME,
    )
INVALID_RAINFALL_DATETIME_ERROR_MESSAGE = \
    INVALID_DATETIME_ERROR_MESSAGE_FORMAT.format(
        RAINFALL_MIN_DATETIME,
    )
INVALID_RELATIVE_HUMIDITY_DATETIME_ERROR_MESSAGE = \
    INVALID_DATETIME_ERROR_MESSAGE_FORMAT.format(
        RELATIVE_HUMIDITY_MIN_DATETIME,
    )
INVALID_TWENTY_FOUR_HOUR_WEATHER_FORECAST_DATETIME_ERROR_MESSAGE = \
    INVALID_DATETIME_ERROR_MESSAGE_FORMAT.format(
        TWENTY_FOUR_HOUR_WEATHER_FORECAST_MIN_DATETIME,
    )
INVALID_TWO_HOUR_WEATHER_FORECAST_DATETIME_ERROR_MESSAGE = \
    INVALID_DATETIME_ERROR_MESSAGE_FORMAT.format(
        TWO_HOUR_WEATHER_FORECAST_MIN_DATETIME,
    )
INVALID_UV_DATETIME_ERROR_MESSAGE = \
    INVALID_DATETIME_ERROR_MESSAGE_FORMAT.format(
        UV_MIN_DATETIME,
    )
INVALID_WBGT_DATETIME_ERROR_MESSAGE = \
    INVALID_DATETIME_ERROR_MESSAGE_FORMAT.format(
        WBGT_MIN_DATETIME,
    )
INVALID_WIND_DIRECTION_DATETIME_ERROR_MESSAGE = \
    INVALID_DATETIME_ERROR_MESSAGE_FORMAT.format(
        WIND_DIRECTION_MIN_DATETIME,
    )
INVALID_WIND_SPEED_DATETIME_ERROR_MESSAGE = \
    INVALID_DATETIME_ERROR_MESSAGE_FORMAT.format(
        WIND_SPEED_MIN_DATETIME,
    )

__all__ = [
    'AIR_TEMPERATURE_API_ENDPOINT',
    'FOUR_DAY_WEATHER_FORECAST_API_ENDPOINT',
    'PM25_API_ENDPOINT',
    'PSI_API_ENDPOINT',
    'RAINFALL_API_ENDPOINT',
    'RELATIVE_HUMIDITY_API_ENDPOINT',
    'TWENTY_FOUR_HOUR_WEATHER_FORECAST_API_ENDPOINT',
    'TWO_HOUR_WEATHER_FORECAST_API_ENDPOINT',
    'UV_INDEX_API_ENDPOINT',
    'WIND_DIRECTION_API_ENDPOINT',
    'WIND_SPEED_API_ENDPOINT',

    'WEATHER_API_ENDPOINT',
    'FLOOD_ALERTS_API_ENDPOINT',

    'LIGHTNING_DEFAULT_PARAMS',
    'WBGT_DEFAULT_PARAMS',

    'WIND_SPEED_SANITISE_IGNORE_KEYS',

    'AIR_TEMPERATURE_MIN_DATETIME',
    'FOUR_DAY_WEATHER_FORECAST_MIN_DATETIME',
    'LIGHTNING_MIN_DATETIME',
    'PM25_MIN_DATETIME',
    'PSI_MIN_DATETIME',
    'RAINFALL_MIN_DATETIME',
    'RELATIVE_HUMIDITY_MIN_DATETIME',
    'UV_MIN_DATETIME',
    'TWENTY_FOUR_HOUR_WEATHER_FORECAST_MIN_DATETIME',
    'TWO_HOUR_WEATHER_FORECAST_MIN_DATETIME',
    'WBGT_MIN_DATETIME',
    'WIND_DIRECTION_MIN_DATETIME',
    'WIND_SPEED_MIN_DATETIME',

    'INVALID_AIR_TEMPERATURE_DATETIME_ERROR_MESSAGE',
    'INVALID_FOUR_DAY_WEATHER_FORECAST_DATETIME_ERROR_MESSAGE',
    'INVALID_LIGHTNING_DATETIME_ERROR_MESSAGE',
    'INVALID_PM25_DATETIME_ERROR_MESSAGE',
    'INVALID_PSI_DATETIME_ERROR_MESSAGE',
    'INVALID_RAINFALL_DATETIME_ERROR_MESSAGE',
    'INVALID_RELATIVE_HUMIDITY_DATETIME_ERROR_MESSAGE',
    'INVALID_TWENTY_FOUR_HOUR_WEATHER_FORECAST_DATETIME_ERROR_MESSAGE',
    'INVALID_TWO_HOUR_WEATHER_FORECAST_DATETIME_ERROR_MESSAGE',
    'INVALID_UV_DATETIME_ERROR_MESSAGE',
    'INVALID_WBGT_DATETIME_ERROR_MESSAGE',
    'INVALID_WIND_DIRECTION_DATETIME_ERROR_MESSAGE',
    'INVALID_WIND_SPEED_DATETIME_ERROR_MESSAGE',
]
